
URLs = {
	'DAVIS': 'https://drive.google.com/uc?export=download&id=14h-0YyHN8lxuc0KV3whsaSaA-4KSmiVN',
	'KIBA': 'https://drive.google.com/uc?export=download&id=1fb3ZI-3_865OuRMWNMzLPnbLm9CktM44',
	'Lipo_AZ': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/lipophilicity.zip',
	'FreeSolv': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/FreeSolv.zip',
	'ESOL': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/ESOL.zip',
	'BBBP': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/bbbp.zip',
	'Tox21': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/tox21.zip',
	'ToxCast': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/toxcast.zip',
	'ClinTox': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/clintox.zip',
	'AqSolDB': 'https://dataverse.harvard.edu/api/access/datafile/3407241?format=original&gbrecs=true',
	'PCBA': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/pcba.zip',
	'MUV': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/muv.zip',
	'HIV': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/hiv.zip',
	'PDBind': 'http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/pdbbind_v2015.tar.gz',
	'BACE': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/bace.zip',
	'BindingDB_Kd': 'https://drugdataloader.s3.amazonaws.com/BindingDB_Kd.csv.zip',
	'BindingDB_Ki': 'https://drugdataloader.s3.amazonaws.com/BindingDB_Ki.csv.zip',
	'BindingDB_IC50': 'https://drugdataloader.s3.amazonaws.com/BindingDB_IC50.csv.zip',
	'BindingDB_EC50': 'https://drugdataloader.s3.amazonaws.com/BindingDB_EC50.csv.zip',
	'QM7': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/qm7b.zip',
	'QM8': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/qm8.zip',
	'QM9': 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/qm9.zip',
	'CathepsinS': 'https://drugdesigndata.org/php/file-download.php?type=extended&id=234'
}
